######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 25 03:33:25 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h camera.h image_process.h W.h
SOURCES += ball.cpp camera.c image_process.c main.cpp W.cpp
