######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 5 14:32:30 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h camera.h image_process.h W.h
SOURCES += ball.cpp camera.c image_process.c main.cpp W.cpp
